<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
    <!-- Prevent CI from updating the lock file if it's outdated -->
    <RestoreLockedMode Condition="'$(CI)' == 'true'">true</RestoreLockedMode>
  </PropertyGroup>

  <ItemGroup>
    <PackageVersion Include="xunit.v3" Version="3.2.2" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="17.13.0" />
    <PackageVersion Include="Elsa" Version="3.7.1" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore" Version="10.0.10" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.10" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Relational" Version="10.0.10" />
    <PackageVersion Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.3" />
    <PackageVersion Include="Aspire.Hosting.AppHost" Version="13.4.6" />
    <PackageVersion Include="Aspire.Hosting.PostgreSQL" Version="13.4.6" />
    <PackageVersion Include="TngTech.ArchUnitNET" Version="0.13.3" />
    <PackageVersion Include="TngTech.ArchUnitNET.xUnitV3" Version="0.13.3" />
    <PackageVersion Include="Testcontainers.PostgreSql" Version="4.13.0" />
    <PackageVersion Include="SSH.NET" Version="2026.0.0" />
  </ItemGroup>
</Project>
