<Project Sdk="Microsoft.NET.Sdk.Web">
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DXOS.Application\DXOS.Application.csproj" />
    <ProjectReference Include="..\DXOS.Infrastructure\DXOS.Infrastructure.csproj" />
    <ProjectReference Include="..\DXOS.Workflows\DXOS.Workflows.csproj" />
  </ItemGroup>
</Project>
