<Project Sdk="Microsoft.NET.Sdk.Web">
  <ItemGroup>
    <ProjectReference Include="..\DXOS.Application\DXOS.Application.csproj" />
    <ProjectReference Include="..\DXOS.Infrastructure\DXOS.Infrastructure.csproj" />
    <ProjectReference Include="..\DXOS.Workflows\DXOS.Workflows.csproj" />
  </ItemGroup>
</Project>
